from django.urls import path
from . import views

app_name = 'catalog'

urlpatterns = [
    path('dashboard/', views.index, name='dashboard'),
    path("catalog/billboard/", views.load_billboard_catalog,
         name="load_billboard_catalog"),
    path("catalog/tv/", views.load_tv_catalog, name="load_tv_catalog"),
    path("catalog/radio/", views.load_radio_catalog, name="load_radio_catalog"),
    path("catalog/cinema/", views.load_cinema_catalog, name="load_cinema_catalog"),
    path("catalog/print/", views.load_print_catalog, name="load_print_catalog"),
    path("add-billboard-unit/", views.add_billboard_unit,
         name="add_billboard_unit"),
    path("upload/form/billboard-image/<int:id>/",
         views.upload_form_billboard_image, name="upload_form_billboard_image"),
    path("upload/excel/billboard-image/", views.upload_excel_billboard_image,
         name="upload_excel_billboard_image"),
    path("update/billboard-image/", views.update_excel_billboard_image,
         name="update_excel_billboard_image"),
    path("update-billboard-unit/<int:pk>/",
         views.edit_billboard_unit, name="edit_billboard_unit"),
    path("delete-billboard-unit/<int:pk>/",
         views.delete_billboard_unit, name="delete_billboard_unit"),
    path("update-tv-unit/<int:pk>/", views.edit_tv_unit, name="edit_tv_unit"),
    path("delete-tv-unit/<int:pk>/", views.delete_tv_unit, name="delete_tv_unit"),
    path("modify-progress-tv-unit/<int:pk>/",
         views.modify_progress_tv_unit, name="modify_progress_tv_unit"),
    path("modify-progress-radio-unit/<int:pk>/",
         views.modify_progress_radio_unit, name="modify_progress_radio_unit"),
    path("modify-progress-billboard-unit/<int:pk>/",
         views.modify_progress_billboard_unit, name="modify_progress_billboard_unit"),
    path("modify-progress-cinema-unit/<int:pk>/",
         views.modify_progress_cinema_unit, name="modify_progress_cinema_unit"),
    path("modify-progress-print-unit/<int:pk>/",
         views.modify_progress_print_unit, name="modify_progress_print_unit"),
    path("see-order-radio-unit/<int:pk>/",
         views.see_order_radio_unit, name="see_order_radio_unit"),
    path("see-order-tv-unit/<int:pk>/",
         views.see_order_tv_unit, name="see_order_tv_unit"),
    path("see-order-print-unit/<int:pk>/",
         views.see_order_print_unit, name="see_order_print_unit"),
    path("see-order-cinema-unit/<int:pk>/",
         views.see_order_cinema_unit, name="see_order_cinema_unit"),
    path("see-order-billboard-unit/<int:pk>/",
         views.see_order_billboard_unit, name="see_order_billboard_unit"),
    path("add-tv-unit/", views.add_tv_unit, name="add_tv_unit"),
    path("update-radio-unit/<int:pk>/",
         views.edit_radio_unit, name="edit_radio_unit"),
    path("delete-radio-unit/<int:pk>/",
         views.delete_radio_unit, name="delete_radio_unit"),
    path("add-radio-unit/", views.add_radio_unit, name="add_radio_unit"),
    path("add-cinema-unit/", views.add_cinema_unit, name="add_cinema_unit"),
    path("add-print-unit/", views.add_print_unit, name="add_print_unit"),
    path("update-print-unit/<int:pk>/",
         views.edit_print_unit, name="edit_print_unit"),
    path("delete-print-unit/<int:pk>/",
         views.delete_print_unit, name="delete_print_unit"),
    path("update-cinema-unit/<int:pk>/",
         views.edit_cinema_unit, name="edit_cinema_unit"),
    path("delete-cinema-unit/<int:pk>/",
         views.delete_cinema_unit, name="delete_cinema_unit"),
    path("upload-static-inventory/", views.upload_billboard_catalog,
         name="upload_billboard_catalog", kwargs={"action": "catalog:upload_billboard_catalog"}),
    path("upload-tv-inventory/", views.upload_tv_catalog,
         name="upload_tv_catalog", kwargs={"action": "catalog:upload_tv_catalog"}),
    path("upload-radio-inventory/", views.upload_radio_catalog,
         name="upload_radio_catalog", kwargs={"action": "catalog:upload_radio_catalog"}),
    path("upload-cinema-inventory/", views.upload_cinema_catalog,
         name="upload_cinema_catalog", kwargs={"action": "catalog:upload_cinema_catalog"}),
    path("upload-print-inventory/", views.upload_print_catalog,
         name="upload_print_catalog", kwargs={"action": "catalog:upload_print_catalog"}),
    path("profile/", views.profile, name="profile"),
    path("faq/", views.faqs, name="faqs"),
    path("staffs/", views.staff_users, name="staff_users"),
    path("staffs/invites/pending/",
         views.pending_staff_invites, name="pending_invite"),
    path("staffs/invites/accepted/",
         views.accepted_staff_invites, name="accepted_invite"),
    path("catalog/special-offers/", views.load_special_offers,
         name="load_special_offers"),
    path("add-special-offer/", views.add_special_offer, name="add_special_offer"),
    path("update-special-offer/<int:pk>/",
         views.edit_special_offer, name="edit_special_offer"),
    path("delete-special-offer/<int:pk>/",
         views.delete_special_offer, name="delete_special_offer"),
]
