apiVersion: v1
kind: Service
metadata:
  name: adzmart-ecommerce-frontend
spec:
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8181
  selector:
    app: adzmart-ecommerce-frontend
