steps:
  - name: node:16
    entrypoint: yarn
    args: ['install']
    timeout: 600s
  - name: node:16
    entrypoint: yarn
    args: ['run', 'build']
    timeout: 600s

options:
  logging: CLOUD_LOGGING_ONLY
