apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service.yaml
  - deployment.yaml
configMapGenerator:
  - name: adzmart-supply-side-templates
    files:
      - confd/templates/config.yaml.tmpl
