# Generated by Django 4.0.5 on 2022-07-12 23:05

import apps.authentication.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('company_location', models.CharField(blank=True, max_length=255, null=True)),
                ('rc_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='RC Number')),
                ('government_id', models.FileField(upload_to=apps.authentication.models.user_directory_path, verbose_name='Government ID')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
