# Generated by Django 4.0.5 on 2022-07-13 04:04

import apps.authentication.models
import apps.catalog.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='government_id',
            field=models.FileField(upload_to=apps.authentication.models.user_directory_path, validators=[apps.catalog.utilities.validate_file_size], verbose_name='Government ID'),
        ),
    ]
