# Generated by Django 4.0.5 on 2022-07-15 15:22

import apps.authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_supplier_government_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='government_id',
            field=models.FileField(upload_to=apps.authentication.models.user_directory_path, verbose_name='Government ID'),
        ),
    ]
