# Generated by Django 4.0.5 on 2022-09-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_invitation'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(fields=('email', 'supplier'), name='email_supplier_unique'),
        ),
    ]
