# Generated by Django 4.1 on 2022-09-10 16:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MediaAdvisory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=50)),
                ("company_name", models.CharField(max_length=50)),
                ("is_existing_customer", models.BooleanField(default=False)),
                (
                    "preferred_contact_method",
                    models.CharField(
                        choices=[("Phone", "Phone"), ("Email", "Email")], max_length=50
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("Outdoor", "Outdoor"),
                            ("Radio", "Radio"),
                            ("Television", "Television"),
                            ("Print", "Print"),
                            ("Mobile", "Online/Mobile"),
                            ("Cinema", "Cinema"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "planned_budget",
                    models.CharField(
                        choices=[
                            ("N200,000 - N500,000", "N200,000 - N500,000"),
                            ("N500,000 - N1,000,000", "N500,000 - N1,000,000"),
                            ("N1,000,000 - N2,000,000", "N1,000,000 - N2,000,000"),
                            ("N1,000,000 - N2,000,000", "N1,000,000 - N2,000,000"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "advertising_experience",
                    models.CharField(
                        choices=[
                            (
                                "I have already booked advertising myself several times",
                                "I have already booked advertising myself several times",
                            ),
                            (
                                "So far I have only booked advertising through agencies",
                                "So far I have only booked advertising through agencies",
                            ),
                            (
                                "I want to book advertising for the first time",
                                "I want to book advertising for the first time",
                            ),
                            (
                                "I have no experience so far and only need information at first",
                                "I have no experience so far and only need information at first",
                            ),
                        ],
                        max_length=255,
                    ),
                ),
                ("additional_info", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Media Advisory",
            },
        ),
        migrations.CreateModel(
            name="MediaBrief",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=50)),
                ("company_name", models.CharField(max_length=50)),
                ("is_existing_customer", models.BooleanField(default=False)),
                (
                    "preferred_contact_method",
                    models.CharField(
                        choices=[("Phone", "Phone"), ("Email", "Email")], max_length=50
                    ),
                ),
                ("campaign_details", models.TextField()),
                ("target_audience", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=100)),
                ("duration", models.TextField()),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("Outdoor", "Outdoor"),
                            ("Radio", "Radio"),
                            ("Television", "Television"),
                            ("Print", "Print"),
                            ("Mobile", "Online/Mobile"),
                            ("Cinema", "Cinema"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Media Briefs",
            },
        ),
        migrations.CreateModel(
            name="Support",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=50)),
                ("company_name", models.CharField(max_length=50)),
                ("is_existing_customer", models.BooleanField(default=False)),
                (
                    "preferred_contact_method",
                    models.CharField(
                        choices=[("Phone", "Phone"), ("Email", "Email")], max_length=50
                    ),
                ),
                ("request_info", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Support",
            },
        ),
    ]
